import { existsSync, readFileSync } from 'node:fs'
import { defineConfig } from 'vitest/config'

/** Local-development alias table generated by scripts/setup-dev.mjs. */
function dshAliases(): Record<string, string> | undefined {
  const file = new URL('./dsh.paths.json', import.meta.url)
  if (!existsSync(file)) return undefined
  const { compilerOptions } = JSON.parse(readFileSync(file, 'utf8')) as {
    compilerOptions: { paths: Record<string, string[]> }
  }
  const aliases: Record<string, string> = {}
  for (const [specifier, targets] of Object.entries(compilerOptions.paths)) {
    // Exact keys only; each entry maps to one harness source file.
    if (!specifier.endsWith('/client') && targets[0] !== undefined) {
      aliases[specifier] = new URL(targets[0]!.replace(/\.ts$/, '.ts'), file).pathname
    }
    for (const target of targets) {
      if (specifier.endsWith('/client') || target.includes('/client/')) {
        aliases[specifier] = new URL(target, file).pathname
      }
    }
  }
  return aliases
}

const aliases = dshAliases()

export default defineConfig({
  resolve: aliases === undefined ? {} : { alias: aliases },
  test: {
    include: ['tests/**/*.spec.ts', 'tests/**/*.spec.tsx'],
    environment: 'node',
  },
})
